name: .NET CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: Restore dependencies
        run: dotnet restore AuthSystem.sln

      - name: Clean project
        run: dotnet clean AuthSystem.sln

      - name: Build project
        run: dotnet build AuthSystem.sln --configuration Release --no-restore /p:EnableWindowsTargeting=true

      - name: Run tests
        run: dotnet test AuthSystem.sln --no-restore --verbosity normal

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Verify secrets
        run: |
          if [ -z "${{ secrets.SSH_KEY }}" ] || [ -z "${{ secrets.HOST }}" ] || [ -z "${{ secrets.USERNAME }}" ] || [ -z "${{ secrets.DEPLOY_PATH }}" ]; then
            echo "Missing SSH_KEY, HOST, USERNAME, or DEPLOY_PATH secret."
            exit 1
          fi

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Test SSH connection
        run: |
          ssh -T ${{ secrets.USERNAME }}@${{ secrets.HOST }}

      - name: Deploy via SSH
        run: |
          ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} "cd ${{ secrets.DEPLOY_PATH }} && bash deploy.sh"
